name: Mirror SVN to Git

on:
  schedule:
    # Run every 6 hours (adjust as needed)
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  svn-mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install svn and git
        run: sudo apt-get update && sudo apt-get install -y subversion git

      - name: Clone or fetch from SVN with git-svn
        run: |
          if [ ! -d repo ]; then
            git svn clone --stdlayout https://svn.code.sf.net/p/lame/svn/trunk repo
          else
            cd repo
            git svn rebase
          fi

      - name: Push to GitHub
        run: |
          cd repo
          git remote add origin "git@github.com:${{ github.repository }}.git" || true
          git push origin refs/remotes/git-svn:refs/heads/master --force
